version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:14.15.5
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: fetch dependencies
          command: yarn install --no-progress --non-interactive --silent --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: format check
          command: yarn format:check
      - run:
          name: test
          command: yarn nx run-many --target=test --projects=sin-nihongo,api,sin-nihongo-lib
      - store_artifacts:
          path: test-results.xml
      - store_test_results:
          path: test-results.xml

workflows:
  deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          force: true
          requires:
            - build
          filters:
            branches:
              only: main
